
apiVersion: argoproj.io/v1alpha1   # API group for ArgoCD resources
kind: Application                  # Resource type is "Application"
metadata:
  name: apache-declarative-app            # Name of this ArgoCD application
  namespace: argocd                # Must be created in the 'argocd' namespace
spec:
  project: default                 # ArgoCD Project (logical grouping of apps)
  source:
    repoURL: https://github.com/dushyantkumark/argocd-in-one-shot.git   # Git repo containing manifests
    targetRevision: feature/implementation           # Git branch or tag (e.g., main, dev, release-1.0)
    path: 04_first_app_deployment/declarative_approach/apache   # Path inside repo where manifests live
  destination:
    server: <argocd_cluster_server_url>   # Target cluster API
    namespace: apache             # Namespace in which to deploy the app
  syncPolicy:                      # Defines how ArgoCD syncs the app
    automated:                     # Enable auto-sync
      prune: true                  # Delete resources removed from Git
      selfHeal: true               # Fix drift if resources are changed manually
